package ventanas;

import clases.Declaraciones;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

public class VentanaInicio extends javax.swing.JFrame {

    JFrame vent = this;

    /**
     * Creates new form VentanaInicio
     *
     *
     */
    public VentanaInicio(int i) {

    }

    public VentanaInicio() {
        initComponents();
        ImageIcon icono = new ImageIcon("src\\Imagenes\\icono.jpg");
        this.setIconImage(icono.getImage());
        getContentPane().setBackground(java.awt.Color.GRAY);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textoPlazas = new javax.swing.JTextField();
        textoTiempo = new javax.swing.JTextField();
        botonAceptarV1 = new javax.swing.JButton();
        botonLimpiarV1 = new javax.swing.JButton();
        botonSalirV1 = new javax.swing.JButton();
        LabelInformacion = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("BIENVENIDO A LA APP PARKING");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 31, 316, 36));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("INTRODUZCA EL NUMERO DE PLAZAS :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 93, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText(" TIEMPO QUE ESTARA ABIERTO EL PARKING:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 162, 410, 30));

        textoPlazas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(textoPlazas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 60, -1));

        textoTiempo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(textoTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 60, -1));

        botonAceptarV1.setText("ACEPTAR");
        botonAceptarV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarV1ActionPerformed(evt);
            }
        });
        getContentPane().add(botonAceptarV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 91, 41));

        botonLimpiarV1.setText("LIMPIAR");
        botonLimpiarV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarV1ActionPerformed(evt);
            }
        });
        getContentPane().add(botonLimpiarV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 93, 40));

        botonSalirV1.setText("SALIR");
        botonSalirV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirV1ActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalirV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 101, 40));
        getContentPane().add(LabelInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 234, 262, 35));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicio.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarV1ActionPerformed
        // TODO add your handling code here:
        if (textoPlazas.getText().isEmpty() || textoTiempo.getText().isEmpty()) {

            LabelInformacion.setText("DEBE INTRODUCIR AMBOS DATOS");

        } else {
            System.out.println(textoPlazas.getText());
            Declaraciones.setNumPlazas(Integer.parseInt(textoPlazas.getText()));
            System.out.println(textoTiempo.getText());
            Declaraciones.setTiempo(Integer.parseInt(textoTiempo.getText()));

            new Declaraciones();
            new VentanaVisualizacion().setVisible(true);
            // new VentanaTemporizador().setVisible(true);

            this.dispose();
        }

    }//GEN-LAST:event_botonAceptarV1ActionPerformed

    private void botonLimpiarV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarV1ActionPerformed
        // TODO add your handling code here:
        textoPlazas.setText("");
        textoTiempo.setText("");
    }//GEN-LAST:event_botonLimpiarV1ActionPerformed

    private void botonSalirV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirV1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonSalirV1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelInformacion;
    private javax.swing.JButton botonAceptarV1;
    private javax.swing.JButton botonLimpiarV1;
    private javax.swing.JButton botonSalirV1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField textoPlazas;
    private javax.swing.JTextField textoTiempo;
    // End of variables declaration//GEN-END:variables
}
