package ventanas;

import clases.Declaraciones;
import java.awt.Color;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class VentanaFinal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaFinal
     */
    int numCochesEntrado, numCochesMasDeUna, tiempoTotal, dineroIngresado;

    public VentanaFinal() {
        initComponents();
        ImageIcon icono = new ImageIcon("src\\Imagenes\\icono.jpg");
        this.setIconImage(icono.getImage());
        btnSalirlir.setBackground(Color.RED);
        numCochesEntrado = Declaraciones.getNumCochesEntrados();
        numCochesMasDeUna = Declaraciones.getContMasDeUna();
        tiempoTotal = Declaraciones.getTiempoTotal();
        calcularIngreso();
        pintarDatos();
        getContentPane().setBackground(java.awt.Color.GRAY);
        this.setLocationRelativeTo(null);
        this.setResizable(false);

    }

    private void calcularIngreso() {
        dineroIngresado = (int) (tiempoTotal * 0.5);
    }

    private void pintarDatos() {
        c1.setText("" + numCochesEntrado);
        c2.setText("" + numCochesMasDeUna);
        c3.setText("" + tiempoTotal);
        c4.setText("" + dineroIngresado + " €");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        c1 = new javax.swing.JTextField();
        c2 = new javax.swing.JTextField();
        c4 = new javax.swing.JTextField();
        c3 = new javax.swing.JTextField();
        btnSalirlir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("NºCOCHES QUE HAN ENTRADO: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 290, -1));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("COCHES QUE HAN ENTRADO MAS DE UNA VEZ: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, 24));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("TIEMPO TOTAL DE APARCAMIENTO DE TODOS LOS COCHES: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("A 0.5 POR SEGUNDO, SUMAN UN INGRESO TOTAL DE :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        c1.setEditable(false);
        c1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 70, -1));

        c2.setEditable(false);
        c2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 70, -1));

        c4.setEditable(false);
        c4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 74, -1));

        c3.setEditable(false);
        c3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 70, -1));

        btnSalirlir.setText("CERRAR");
        btnSalirlir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirlirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalirlir, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 312, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/final.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirlirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirlirActionPerformed
        JOptionPane.showMessageDialog(null, "SALIMOS DE LA APP. GRACIAS POR SU VISITA.");
        System.exit(0);
    }//GEN-LAST:event_btnSalirlirActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalirlir;
    private javax.swing.JTextField c1;
    private javax.swing.JTextField c2;
    private javax.swing.JTextField c3;
    private javax.swing.JTextField c4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

}
